spring:
  application:
    name: monitoring-service

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
