server:
  port: 8080
  forward-headers-strategy: native

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: api
  main:
    locale: ko_KR
  messages:
    basename: messages
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:create-drop}
    properties:
      hibernate:
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  data:
    web:
      pageable:
        default-page-size: 20
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 600000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}

cloud:
  aws:
    region:
      static: ${AWS_REGION:ap-northeast-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    stack:
      auto: false

applydays:
  notification:
    email:
      trigger-queue: ${APPLYDAYS_TRIGGER_QUEUE}

app:
  woorimail:
    server-url: ${WOORIMAIL_SERVER_URL}
    ssl: ${WOORIMAIL_SSL}
    ssl-port: ${WOORIMAIL_SSL_PORT}
    authkey: ${WOORIMAIL_AUTHKEY}
    domain: ${WOORIMAIL_DOMAIN}
    type: ${WOORIMAIL_TYPE}
    mid: ${WOORIMAIL_MID}
    endpoint: ${WOORIMAIL_ENDPOINT}
    act: ${WOORIMAIL_ACT}
    sender-email: ${WOORIMAIL_SENDER_EMAIL}
    sender-nickname: ${WOORIMAIL_SENDER_NICKNAME}
    wms-domain: ${WOORIMAIL_WMS_DOMAIN}
    wms-nick: ${WOORIMAIL_WMS_NICK}
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI}
  crypto:
    key: ${CRYPTO_KEY}
    iv: ${CRYPTO_IV}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

cloudflare:
  r2:
    token: ${CLOUDFLARE_TOKEN}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
    image-path: ${CLOUDFLARE_R2_IMAGE_PATH}

logging:
  level:
    com.services: INFO
